// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_scrMain.h"
#include "screens/ui_scrSettings.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bkgrnd5_png);    // assets/bkgrnd5.png
LV_IMG_DECLARE(ui_img_battt_png);    // assets/battt.png
LV_IMG_DECLARE(ui_img_963419959);    // assets/car-battery (1).png
LV_IMG_DECLARE(ui_img_cruise_png);    // assets/cruise.png
LV_IMG_DECLARE(ui_img_258024724);    // assets/brake (1).png
LV_IMG_DECLARE(ui_img_1559759506);    // assets/icons8-bluetooth-32 (1).png
LV_IMG_DECLARE(ui_img_speedometer_png);    // assets/speedometer.png
LV_IMG_DECLARE(ui_img_1698700558);    // assets/speedometer (1).png
LV_IMG_DECLARE(ui_img_1930944701);    // assets/technology (1).png

// FONTS
LV_FONT_DECLARE(ui_font_Moscow14);
LV_FONT_DECLARE(ui_font_Moscow16);
LV_FONT_DECLARE(ui_font_Moscow24);
LV_FONT_DECLARE(ui_font_Moscow28);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
