// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: FT85BD_DASH

#ifndef _FT85BD_DASH_UI_H
#define _FT85BD_DASH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_mainScreen.h"
#include "screens/ui_infoScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
