// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: FT85BD_DASH

#include "../ui.h"

lv_obj_t * ui_infoScreen = NULL;
lv_obj_t * ui_lblFirmware = NULL;
lv_obj_t * ui_lblSpeedGear = NULL;
lv_obj_t * ui_lblDirection = NULL;
lv_obj_t * ui_lblCruise = NULL;
lv_obj_t * ui_lblMultiMode = NULL;
lv_obj_t * ui_lblCpu = NULL;
lv_obj_t * ui_lblEncoder = NULL;
lv_obj_t * ui_lblPasRpm = NULL;
lv_obj_t * ui_lblErrorCode = NULL;
lv_obj_t * ui_lblControllerId = NULL;
lv_obj_t * ui_btnBack = NULL;
// event funtions
void ui_event_btnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_mainScreen_screen_init);
    }
}

// build funtions

void ui_infoScreen_screen_init(void)
{
    ui_infoScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_infoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblFirmware = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblFirmware, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFirmware, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFirmware, -119);
    lv_obj_set_y(ui_lblFirmware, -198);
    lv_obj_set_align(ui_lblFirmware, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFirmware, "firmware");

    ui_lblSpeedGear = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblSpeedGear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSpeedGear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSpeedGear, -138);
    lv_obj_set_y(ui_lblSpeedGear, -176);
    lv_obj_set_align(ui_lblSpeedGear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSpeedGear, "Gear");

    ui_lblDirection = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblDirection, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDirection, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDirection, -118);
    lv_obj_set_y(ui_lblDirection, -154);
    lv_obj_set_align(ui_lblDirection, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDirection, "Direction");

    ui_lblCruise = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblCruise, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCruise, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCruise, -130);
    lv_obj_set_y(ui_lblCruise, -131);
    lv_obj_set_align(ui_lblCruise, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCruise, "Cruise");

    ui_lblMultiMode = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblMultiMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMultiMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMultiMode, -134);
    lv_obj_set_y(ui_lblMultiMode, -109);
    lv_obj_set_align(ui_lblMultiMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMultiMode, "Mode");

    ui_lblCpu = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblCpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCpu, -140);
    lv_obj_set_y(ui_lblCpu, -86);
    lv_obj_set_align(ui_lblCpu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCpu, "Cpu");

    ui_lblEncoder = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblEncoder, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblEncoder, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblEncoder, -138);
    lv_obj_set_y(ui_lblEncoder, -62);
    lv_obj_set_align(ui_lblEncoder, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblEncoder, "Enc");

    ui_lblPasRpm = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblPasRpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPasRpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPasRpm, -122);
    lv_obj_set_y(ui_lblPasRpm, -41);
    lv_obj_set_align(ui_lblPasRpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPasRpm, "Pas rpm");

    ui_lblErrorCode = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblErrorCode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblErrorCode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblErrorCode, -139);
    lv_obj_set_y(ui_lblErrorCode, -18);
    lv_obj_set_align(ui_lblErrorCode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblErrorCode, "Err");

    ui_lblControllerId = lv_label_create(ui_infoScreen);
    lv_obj_set_width(ui_lblControllerId, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblControllerId, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblControllerId, -129);
    lv_obj_set_y(ui_lblControllerId, 5);
    lv_obj_set_align(ui_lblControllerId, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblControllerId, "ESC ID");

    ui_btnBack = lv_button_create(ui_infoScreen);
    lv_obj_set_width(ui_btnBack, 100);
    lv_obj_set_height(ui_btnBack, 50);
    lv_obj_set_x(ui_btnBack, -99);
    lv_obj_set_y(ui_btnBack, 201);
    lv_obj_set_align(ui_btnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_btnBack, ui_event_btnBack, LV_EVENT_ALL, NULL);

}

void ui_infoScreen_screen_destroy(void)
{
    if(ui_infoScreen) lv_obj_del(ui_infoScreen);

    // NULL screen variables
    ui_infoScreen = NULL;
    ui_lblFirmware = NULL;
    ui_lblSpeedGear = NULL;
    ui_lblDirection = NULL;
    ui_lblCruise = NULL;
    ui_lblMultiMode = NULL;
    ui_lblCpu = NULL;
    ui_lblEncoder = NULL;
    ui_lblPasRpm = NULL;
    ui_lblErrorCode = NULL;
    ui_lblControllerId = NULL;
    ui_btnBack = NULL;

}

void ui_infoScreen_screen_relocalize(void)
{
    // label widgets on screen

}
