// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: FT85BD_DASH

#ifndef UI_INFOSCREEN_H
#define UI_INFOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_infoScreen
extern void ui_infoScreen_screen_init(void);
extern void ui_infoScreen_screen_destroy(void);
extern void ui_infoScreen_screen_relocalize(void);
extern lv_obj_t * ui_infoScreen;
extern lv_obj_t * ui_lblFirmware;
extern lv_obj_t * ui_lblSpeedGear;
extern lv_obj_t * ui_lblDirection;
extern lv_obj_t * ui_lblCruise;
extern lv_obj_t * ui_lblMultiMode;
extern lv_obj_t * ui_lblCpu;
extern lv_obj_t * ui_lblEncoder;
extern lv_obj_t * ui_lblPasRpm;
extern lv_obj_t * ui_lblErrorCode;
extern lv_obj_t * ui_lblControllerId;
extern void ui_event_btnBack(lv_event_t * e);
extern lv_obj_t * ui_btnBack;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

