// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: FT85BD_DASH

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainScreen
extern void ui_mainScreen_screen_init(void);
extern void ui_mainScreen_screen_destroy(void);
extern void ui_mainScreen_screen_relocalize(void);
extern lv_obj_t * ui_mainScreen;
extern lv_obj_t * ui_lblSpeed;
extern lv_obj_t * ui_lblKmh;
extern lv_obj_t * ui_lblWatt;
extern lv_obj_t * ui_lblVolt;
extern lv_obj_t * ui_lblCurrent;
extern lv_obj_t * ui_lblTemp;
extern lv_obj_t * ui_lblPas;
extern lv_obj_t * ui_contStatus;
extern lv_obj_t * ui_lblBT;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui_lblBat;
extern lv_obj_t * ui_lblRpm;
extern lv_obj_t * ui_lblMotorTmp;
extern lv_obj_t * ui_lblFault;
extern lv_obj_t * ui_lblTrip;
extern lv_obj_t * ui_lblOdo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

