// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: FT85BD_DASH

#include "../ui.h"

lv_obj_t * ui_mainScreen = NULL;
lv_obj_t * ui_lblSpeed = NULL;
lv_obj_t * ui_lblKmh = NULL;
lv_obj_t * ui_lblWatt = NULL;
lv_obj_t * ui_lblVolt = NULL;
lv_obj_t * ui_lblCurrent = NULL;
lv_obj_t * ui_lblTemp = NULL;
lv_obj_t * ui_lblPas = NULL;
lv_obj_t * ui_contStatus = NULL;
lv_obj_t * ui_lblBT = NULL;
lv_obj_t * ui_lblTime = NULL;
lv_obj_t * ui_lblBat = NULL;
lv_obj_t * ui_lblRpm = NULL;
lv_obj_t * ui_lblMotorTmp = NULL;
lv_obj_t * ui_lblFault = NULL;
lv_obj_t * ui_lblTrip = NULL;
lv_obj_t * ui_lblOdo = NULL;
// event funtions

// build funtions

void ui_mainScreen_screen_init(void)
{
    ui_mainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_mainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSpeed = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSpeed, 0);
    lv_obj_set_y(ui_lblSpeed, -120);
    lv_obj_set_align(ui_lblSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSpeed, "45");
    lv_obj_set_style_text_color(ui_lblSpeed, lv_color_hex(0xF1EC05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSpeed, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblKmh = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblKmh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblKmh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblKmh, 0);
    lv_obj_set_y(ui_lblKmh, -81);
    lv_obj_set_align(ui_lblKmh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblKmh, "km/h");

    ui_lblWatt = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblWatt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWatt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWatt, 0);
    lv_obj_set_y(ui_lblWatt, -53);
    lv_obj_set_align(ui_lblWatt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWatt, "750W");
    lv_obj_set_style_text_color(ui_lblWatt, lv_color_hex(0xE27E0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWatt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWatt, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVolt = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblVolt, 0);
    lv_obj_set_y(ui_lblVolt, -25);
    lv_obj_set_align(ui_lblVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVolt, "Voltage: 54.2V");

    ui_lblCurrent = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCurrent, 0);
    lv_obj_set_y(ui_lblCurrent, -1);
    lv_obj_set_align(ui_lblCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCurrent, "Current: 20A");

    ui_lblTemp = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTemp, 0);
    lv_obj_set_y(ui_lblTemp, 25);
    lv_obj_set_align(ui_lblTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTemp, "Mosfet: 49C");

    ui_lblPas = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblPas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPas, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPas, 0);
    lv_obj_set_y(ui_lblPas, 54);
    lv_obj_set_align(ui_lblPas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPas, "PAS 3");
    lv_obj_set_style_text_color(ui_lblPas, lv_color_hex(0x5ED904), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contStatus = lv_obj_create(ui_mainScreen);
    lv_obj_remove_style_all(ui_contStatus);
    lv_obj_set_width(ui_contStatus, 313);
    lv_obj_set_height(ui_contStatus, 30);
    lv_obj_set_x(ui_contStatus, 0);
    lv_obj_set_y(ui_contStatus, -221);
    lv_obj_set_align(ui_contStatus, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contStatus, lv_color_hex(0x353535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBT = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblBT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBT, -132);
    lv_obj_set_y(ui_lblBT, -221);
    lv_obj_set_align(ui_lblBT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBT, "BT");

    ui_lblTime = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTime, 2);
    lv_obj_set_y(ui_lblTime, -221);
    lv_obj_set_align(ui_lblTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime, "12:45");

    ui_lblBat = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBat, 130);
    lv_obj_set_y(ui_lblBat, -221);
    lv_obj_set_align(ui_lblBat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBat, "84%");

    ui_lblRpm = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblRpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRpm, 0);
    lv_obj_set_y(ui_lblRpm, 79);
    lv_obj_set_align(ui_lblRpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRpm, "750 rpm");

    ui_lblMotorTmp = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblMotorTmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMotorTmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMotorTmp, 0);
    lv_obj_set_y(ui_lblMotorTmp, 103);
    lv_obj_set_align(ui_lblMotorTmp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMotorTmp, "Motor: 39C");

    ui_lblFault = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblFault, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFault, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFault, -125);
    lv_obj_set_y(ui_lblFault, -183);
    lv_obj_set_align(ui_lblFault, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFault, "ERR:0");
    lv_obj_set_style_text_font(ui_lblFault, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTrip = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTrip, 0);
    lv_obj_set_y(ui_lblTrip, 130);
    lv_obj_set_align(ui_lblTrip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTrip, "Trip: 12 km");

    ui_lblOdo = lv_label_create(ui_mainScreen);
    lv_obj_set_width(ui_lblOdo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblOdo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblOdo, 0);
    lv_obj_set_y(ui_lblOdo, 159);
    lv_obj_set_align(ui_lblOdo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblOdo, "ODO: 1321 km");

}

void ui_mainScreen_screen_destroy(void)
{
    if(ui_mainScreen) lv_obj_del(ui_mainScreen);

    // NULL screen variables
    ui_mainScreen = NULL;
    ui_lblSpeed = NULL;
    ui_lblKmh = NULL;
    ui_lblWatt = NULL;
    ui_lblVolt = NULL;
    ui_lblCurrent = NULL;
    ui_lblTemp = NULL;
    ui_lblPas = NULL;
    ui_contStatus = NULL;
    ui_lblBT = NULL;
    ui_lblTime = NULL;
    ui_lblBat = NULL;
    ui_lblRpm = NULL;
    ui_lblMotorTmp = NULL;
    ui_lblFault = NULL;
    ui_lblTrip = NULL;
    ui_lblOdo = NULL;

}

void ui_mainScreen_screen_relocalize(void)
{
    // label widgets on screen

}
