// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_lblSpeed;
extern lv_obj_t * ui_arcSpeed;
extern lv_obj_t * ui_contBatt;
extern lv_obj_t * ui_sldBatt;
extern lv_obj_t * ui_lblGear;
extern lv_obj_t * ui_txtPower;
extern lv_obj_t * ui_lblPower;
extern lv_obj_t * ui_txtGear;
extern lv_obj_t * ui_lblBatt;
extern lv_obj_t * ui_lblPAS;
extern lv_obj_t * ui_txtPAS;
extern lv_obj_t * ui_contVoltage;
extern lv_obj_t * ui_lblVoltage;
extern lv_obj_t * ui_contCruise;
extern lv_obj_t * ui_contBrake;
extern lv_obj_t * ui_contBT;
extern lv_obj_t * ui_txtODO;
extern lv_obj_t * ui_lblODO;
extern lv_obj_t * ui_txtKmh;
extern lv_obj_t * ui_txtTrip;
extern lv_obj_t * ui_lblTrip;
extern lv_obj_t * ui_txtKm2;
extern lv_obj_t * ui_contAVG;
extern lv_obj_t * ui_TxtAVGspd;
extern lv_obj_t * ui_txtAVG;
extern lv_obj_t * ui_lblAVG;
extern lv_obj_t * ui_txtKm3;
extern lv_obj_t * ui_contMAXspd;
extern lv_obj_t * ui_txtMAXspd;
extern lv_obj_t * ui_txtMAX;
extern lv_obj_t * ui_lblMAXspd;
extern lv_obj_t * ui_txtKmh2;
extern lv_obj_t * ui_txtVolt;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

