// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_scrMain = NULL;
lv_obj_t * ui_lblSpeed = NULL;
lv_obj_t * ui_arcSpeed = NULL;
lv_obj_t * ui_contBatt = NULL;
lv_obj_t * ui_sldBatt = NULL;
lv_obj_t * ui_lblGear = NULL;
lv_obj_t * ui_txtPower = NULL;
lv_obj_t * ui_lblPower = NULL;
lv_obj_t * ui_txtGear = NULL;
lv_obj_t * ui_lblBatt = NULL;
lv_obj_t * ui_lblPAS = NULL;
lv_obj_t * ui_txtPAS = NULL;
lv_obj_t * ui_contVoltage = NULL;
lv_obj_t * ui_lblVoltage = NULL;
lv_obj_t * ui_contCruise = NULL;
lv_obj_t * ui_contBrake = NULL;
lv_obj_t * ui_contBT = NULL;
lv_obj_t * ui_txtODO = NULL;
lv_obj_t * ui_lblODO = NULL;
lv_obj_t * ui_txtKmh = NULL;
lv_obj_t * ui_txtTrip = NULL;
lv_obj_t * ui_lblTrip = NULL;
lv_obj_t * ui_txtKm2 = NULL;
lv_obj_t * ui_contAVG = NULL;
lv_obj_t * ui_TxtAVGspd = NULL;
lv_obj_t * ui_txtAVG = NULL;
lv_obj_t * ui_lblAVG = NULL;
lv_obj_t * ui_txtKm3 = NULL;
lv_obj_t * ui_contMAXspd = NULL;
lv_obj_t * ui_txtMAXspd = NULL;
lv_obj_t * ui_txtMAX = NULL;
lv_obj_t * ui_lblMAXspd = NULL;
lv_obj_t * ui_txtKmh2 = NULL;
lv_obj_t * ui_txtVolt = NULL;
// event funtions

// build funtions

void ui_scrMain_screen_init(void)
{
    ui_scrMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrMain, lv_color_hex(0x121416), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_scrMain, &ui_img_bkgrnd5_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSpeed = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSpeed, 2);
    lv_obj_set_y(ui_lblSpeed, -63);
    lv_obj_set_align(ui_lblSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSpeed, "25");
    lv_obj_set_style_text_color(ui_lblSpeed, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_lblSpeed, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_lblSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblSpeed, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSpeed, &ui_font_Moscow24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcSpeed = lv_arc_create(ui_scrMain);
    lv_obj_set_width(ui_arcSpeed, 246);
    lv_obj_set_height(ui_arcSpeed, 257);
    lv_obj_set_x(ui_arcSpeed, 1);
    lv_obj_set_y(ui_arcSpeed, -56);
    lv_obj_set_align(ui_arcSpeed, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_arcSpeed, 35);
    lv_arc_set_bg_angles(ui_arcSpeed, 114, 67);
    lv_obj_set_style_arc_color(ui_arcSpeed, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSpeed, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSpeed, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arcSpeed, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arcSpeed, lv_color_hex(0x8E8E8E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSpeed, 240, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSpeed, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_arcSpeed, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_arcSpeed, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcSpeed, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_contBatt = lv_obj_create(ui_scrMain);
    lv_obj_remove_style_all(ui_contBatt);
    lv_obj_set_width(ui_contBatt, 47);
    lv_obj_set_height(ui_contBatt, 26);
    lv_obj_set_x(ui_contBatt, -128);
    lv_obj_set_y(ui_contBatt, -212);
    lv_obj_set_align(ui_contBatt, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contBatt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_contBatt, &ui_img_battt_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_contBatt, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_contBatt, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_contBatt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sldBatt = lv_slider_create(ui_scrMain);
    lv_slider_set_value(ui_sldBatt, 64, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldBatt) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldBatt, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sldBatt, 39);
    lv_obj_set_height(ui_sldBatt, 20);
    lv_obj_set_x(ui_sldBatt, -130);
    lv_obj_set_y(ui_sldBatt, -212);
    lv_obj_set_align(ui_sldBatt, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_sldBatt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sldBatt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldBatt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_sldBatt, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_sldBatt, lv_color_hex(0x242424), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldBatt, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_sldBatt, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldBatt, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sldBatt, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sldBatt,
                                                                                              lv_obj_get_style_pad_right(ui_sldBatt, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lblGear = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblGear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGear, -130);
    lv_obj_set_y(ui_lblGear, 47);
    lv_obj_set_align(ui_lblGear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGear, "3");
    lv_obj_set_style_text_color(ui_lblGear, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblGear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblGear, &ui_font_Moscow24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtPower = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtPower, 0);
    lv_obj_set_y(ui_txtPower, 26);
    lv_obj_set_align(ui_txtPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtPower, "Power");
    lv_obj_set_style_text_color(ui_txtPower, lv_color_hex(0xEFAE02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPower = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPower, 0);
    lv_obj_set_y(ui_lblPower, 53);
    lv_obj_set_align(ui_lblPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPower, "750");
    lv_obj_set_style_text_color(ui_lblPower, lv_color_hex(0x9A9A9A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPower, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtGear = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtGear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtGear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtGear, -96);
    lv_obj_set_y(ui_txtGear, 64);
    lv_obj_set_align(ui_txtGear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtGear, "SPD");
    lv_obj_set_style_text_color(ui_txtGear, lv_color_hex(0xEFAE02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtGear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBatt = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblBatt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBatt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBatt, -86);
    lv_obj_set_y(ui_lblBatt, -214);
    lv_obj_set_align(ui_lblBatt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBatt, "64");
    lv_obj_set_style_text_color(ui_lblBatt, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblBatt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblBatt, &ui_font_Moscow16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPAS = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblPAS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPAS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPAS, 138);
    lv_obj_set_y(ui_lblPAS, 47);
    lv_obj_set_align(ui_lblPAS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPAS, "5");
    lv_obj_set_style_text_color(ui_lblPAS, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblPAS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPAS, &ui_font_Moscow24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtPAS = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtPAS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtPAS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtPAS, 94);
    lv_obj_set_y(ui_txtPAS, 65);
    lv_obj_set_align(ui_txtPAS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtPAS, "PAS");
    lv_obj_set_style_text_color(ui_txtPAS, lv_color_hex(0xEFAE02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtPAS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contVoltage = lv_obj_create(ui_scrMain);
    lv_obj_remove_style_all(ui_contVoltage);
    lv_obj_set_width(ui_contVoltage, 33);
    lv_obj_set_height(ui_contVoltage, 32);
    lv_obj_set_x(ui_contVoltage, 1);
    lv_obj_set_y(ui_contVoltage, 114);
    lv_obj_set_align(ui_contVoltage, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contVoltage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_contVoltage, &ui_img_963419959, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_contVoltage, lv_color_hex(0x01AACD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_contVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVoltage = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblVoltage, -5);
    lv_obj_set_y(ui_lblVoltage, 145);
    lv_obj_set_align(ui_lblVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVoltage, "54.4");
    lv_obj_set_style_text_font(ui_lblVoltage, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contCruise = lv_obj_create(ui_scrMain);
    lv_obj_remove_style_all(ui_contCruise);
    lv_obj_set_width(ui_contCruise, 29);
    lv_obj_set_height(ui_contCruise, 29);
    lv_obj_set_x(ui_contCruise, 90);
    lv_obj_set_y(ui_contCruise, -211);
    lv_obj_set_align(ui_contCruise, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contCruise, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_contCruise, &ui_img_cruise_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_contCruise, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_contCruise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contBrake = lv_obj_create(ui_scrMain);
    lv_obj_remove_style_all(ui_contBrake);
    lv_obj_set_width(ui_contBrake, 30);
    lv_obj_set_height(ui_contBrake, 27);
    lv_obj_set_x(ui_contBrake, 129);
    lv_obj_set_y(ui_contBrake, -211);
    lv_obj_set_align(ui_contBrake, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contBrake, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_contBrake, &ui_img_258024724, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_contBrake, lv_color_hex(0x242424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_contBrake, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contBT = lv_obj_create(ui_scrMain);
    lv_obj_remove_style_all(ui_contBT);
    lv_obj_set_width(ui_contBT, 27);
    lv_obj_set_height(ui_contBT, 27);
    lv_obj_set_x(ui_contBT, -20);
    lv_obj_set_y(ui_contBT, -218);
    lv_obj_set_align(ui_contBT, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contBT, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_contBT, &ui_img_1559759506, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_contBT, lv_color_hex(0x01AACD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_contBT, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtODO = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtODO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtODO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtODO, 23);
    lv_obj_set_y(ui_txtODO, 217);
    lv_obj_set_align(ui_txtODO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtODO, "ODO");
    lv_obj_set_style_text_color(ui_txtODO, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtODO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtODO, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblODO = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblODO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblODO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblODO, 85);
    lv_obj_set_y(ui_lblODO, 215);
    lv_obj_set_align(ui_lblODO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblODO, "1325.7");
    lv_obj_set_style_text_color(ui_lblODO, lv_color_hex(0xD69D05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblODO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblODO, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtKmh = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtKmh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtKmh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtKmh, 136);
    lv_obj_set_y(ui_txtKmh, 219);
    lv_obj_set_align(ui_txtKmh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtKmh, "Km");
    lv_obj_set_style_text_color(ui_txtKmh, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtKmh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtKmh, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtTrip = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtTrip, -133);
    lv_obj_set_y(ui_txtTrip, 217);
    lv_obj_set_align(ui_txtTrip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtTrip, "TRIP");
    lv_obj_set_style_text_color(ui_txtTrip, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtTrip, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTrip = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTrip, -79);
    lv_obj_set_y(ui_lblTrip, 215);
    lv_obj_set_align(ui_lblTrip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTrip, "37.4");
    lv_obj_set_style_text_color(ui_lblTrip, lv_color_hex(0x048CA9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTrip, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtKm2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtKm2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtKm2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtKm2, -31);
    lv_obj_set_y(ui_txtKm2, 219);
    lv_obj_set_align(ui_txtKm2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtKm2, "Km");
    lv_obj_set_style_text_color(ui_txtKm2, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtKm2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtKm2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contAVG = lv_obj_create(ui_scrMain);
    lv_obj_remove_style_all(ui_contAVG);
    lv_obj_set_width(ui_contAVG, 38);
    lv_obj_set_height(ui_contAVG, 33);
    lv_obj_set_x(ui_contAVG, -134);
    lv_obj_set_y(ui_contAVG, 115);
    lv_obj_set_align(ui_contAVG, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contAVG, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_contAVG, &ui_img_speedometer_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_contAVG, lv_color_hex(0x4CDA44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_contAVG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TxtAVGspd = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_TxtAVGspd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TxtAVGspd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TxtAVGspd, -86);
    lv_obj_set_y(ui_TxtAVGspd, 117);
    lv_obj_set_align(ui_TxtAVGspd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TxtAVGspd, "Speed");
    lv_obj_set_style_text_color(ui_TxtAVGspd, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TxtAVGspd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtAVG = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtAVG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtAVG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtAVG, -134);
    lv_obj_set_y(ui_txtAVG, 142);
    lv_obj_set_align(ui_txtAVG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtAVG, "AVG");
    lv_obj_set_style_text_color(ui_txtAVG, lv_color_hex(0x4CDA44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtAVG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblAVG = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblAVG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAVG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAVG, -99);
    lv_obj_set_y(ui_lblAVG, 143);
    lv_obj_set_align(ui_lblAVG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAVG, "19");
    lv_obj_set_style_text_font(ui_lblAVG, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtKm3 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtKm3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtKm3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtKm3, -71);
    lv_obj_set_y(ui_txtKm3, 148);
    lv_obj_set_align(ui_txtKm3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtKm3, "km\\h");
    lv_obj_set_style_text_color(ui_txtKm3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtKm3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtKm3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contMAXspd = lv_obj_create(ui_scrMain);
    lv_obj_remove_style_all(ui_contMAXspd);
    lv_obj_set_width(ui_contMAXspd, 36);
    lv_obj_set_height(ui_contMAXspd, 31);
    lv_obj_set_x(ui_contMAXspd, 76);
    lv_obj_set_y(ui_contMAXspd, 112);
    lv_obj_set_align(ui_contMAXspd, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMAXspd, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_contMAXspd, &ui_img_1698700558, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_contMAXspd, lv_color_hex(0xFE4832), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_contMAXspd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtMAXspd = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtMAXspd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtMAXspd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtMAXspd, 123);
    lv_obj_set_y(ui_txtMAXspd, 115);
    lv_obj_set_align(ui_txtMAXspd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtMAXspd, "Speed");
    lv_obj_set_style_text_color(ui_txtMAXspd, lv_color_hex(0x8E8E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtMAXspd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtMAX = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtMAX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtMAX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtMAX, 75);
    lv_obj_set_y(ui_txtMAX, 136);
    lv_obj_set_align(ui_txtMAX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtMAX, "MAX");
    lv_obj_set_style_text_color(ui_txtMAX, lv_color_hex(0xFE4832), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtMAX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMAXspd = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lblMAXspd, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMAXspd, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMAXspd, 107);
    lv_obj_set_y(ui_lblMAXspd, 143);
    lv_obj_set_align(ui_lblMAXspd, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMAXspd, "43");
    lv_obj_set_style_text_font(ui_lblMAXspd, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtKmh2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtKmh2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtKmh2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtKmh2, 137);
    lv_obj_set_y(ui_txtKmh2, 148);
    lv_obj_set_align(ui_txtKmh2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtKmh2, "km\\h");
    lv_obj_set_style_text_color(ui_txtKmh2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtKmh2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_txtKmh2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtVolt = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_txtVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtVolt, 34);
    lv_obj_set_y(ui_txtVolt, 149);
    lv_obj_set_align(ui_txtVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtVolt, "V");

}

void ui_scrMain_screen_destroy(void)
{
    if(ui_scrMain) lv_obj_del(ui_scrMain);

    // NULL screen variables
    ui_scrMain = NULL;
    ui_lblSpeed = NULL;
    ui_arcSpeed = NULL;
    ui_contBatt = NULL;
    ui_sldBatt = NULL;
    ui_lblGear = NULL;
    ui_txtPower = NULL;
    ui_lblPower = NULL;
    ui_txtGear = NULL;
    ui_lblBatt = NULL;
    ui_lblPAS = NULL;
    ui_txtPAS = NULL;
    ui_contVoltage = NULL;
    ui_lblVoltage = NULL;
    ui_contCruise = NULL;
    ui_contBrake = NULL;
    ui_contBT = NULL;
    ui_txtODO = NULL;
    ui_lblODO = NULL;
    ui_txtKmh = NULL;
    ui_txtTrip = NULL;
    ui_lblTrip = NULL;
    ui_txtKm2 = NULL;
    ui_contAVG = NULL;
    ui_TxtAVGspd = NULL;
    ui_txtAVG = NULL;
    ui_lblAVG = NULL;
    ui_txtKm3 = NULL;
    ui_contMAXspd = NULL;
    ui_txtMAXspd = NULL;
    ui_txtMAX = NULL;
    ui_lblMAXspd = NULL;
    ui_txtKmh2 = NULL;
    ui_txtVolt = NULL;

}
