// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCRSETTINGS_H
#define UI_SCRSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSettings
extern void ui_scrSettings_screen_init(void);
extern void ui_scrSettings_screen_destroy(void);
extern lv_obj_t * ui_scrSettings;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_txtESCstatus;
extern lv_obj_t * ui_lblESCstatus;
extern lv_obj_t * ui_txtCPU;
extern lv_obj_t * ui_lblCPU;
extern lv_obj_t * ui_txtMosfetTmp;
extern lv_obj_t * ui_lblMosfetTmp;
extern lv_obj_t * ui_txtERR;
extern lv_obj_t * ui_lblERR;
extern lv_obj_t * ui_txtFW;
extern lv_obj_t * ui_lblFW;
extern lv_obj_t * ui_contGear;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

