// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_scrSettings = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_txtESCstatus = NULL;
lv_obj_t * ui_lblESCstatus = NULL;
lv_obj_t * ui_txtCPU = NULL;
lv_obj_t * ui_lblCPU = NULL;
lv_obj_t * ui_txtMosfetTmp = NULL;
lv_obj_t * ui_lblMosfetTmp = NULL;
lv_obj_t * ui_txtERR = NULL;
lv_obj_t * ui_lblERR = NULL;
lv_obj_t * ui_txtFW = NULL;
lv_obj_t * ui_lblFW = NULL;
lv_obj_t * ui_contGear = NULL;
// event funtions

// build funtions

void ui_scrSettings_screen_init(void)
{
    ui_scrSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scrSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_scrSettings);
    lv_obj_set_width(ui_Panel1, 293);
    lv_obj_set_height(ui_Panel1, 37);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -190);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x171A1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_scrSettings);
    lv_obj_set_width(ui_Panel2, 293);
    lv_obj_set_height(ui_Panel2, 37);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -140);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x171A1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_scrSettings);
    lv_obj_set_width(ui_Panel3, 293);
    lv_obj_set_height(ui_Panel3, 37);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, -90);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x171A1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_scrSettings);
    lv_obj_set_width(ui_Panel4, 293);
    lv_obj_set_height(ui_Panel4, 37);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -40);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x171A1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_scrSettings);
    lv_obj_set_width(ui_Panel5, 293);
    lv_obj_set_height(ui_Panel5, 37);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, 10);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x171A1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_scrSettings);
    lv_obj_set_width(ui_Panel6, 298);
    lv_obj_set_height(ui_Panel6, 136);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 122);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_txtESCstatus = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_txtESCstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtESCstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtESCstatus, -122);
    lv_obj_set_y(ui_txtESCstatus, -189);
    lv_obj_set_align(ui_txtESCstatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtESCstatus, "ESC:");

    ui_lblESCstatus = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_lblESCstatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblESCstatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblESCstatus, -76);
    lv_obj_set_y(ui_lblESCstatus, -189);
    lv_obj_set_align(ui_lblESCstatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblESCstatus, "ONLINE");

    ui_txtCPU = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_txtCPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtCPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtCPU, -121);
    lv_obj_set_y(ui_txtCPU, -140);
    lv_obj_set_align(ui_txtCPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtCPU, "CPU:");

    ui_lblCPU = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_lblCPU, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCPU, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCPU, -81);
    lv_obj_set_y(ui_lblCPU, -140);
    lv_obj_set_align(ui_lblCPU, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCPU, "12.5%");

    ui_txtMosfetTmp = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_txtMosfetTmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtMosfetTmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtMosfetTmp, -95);
    lv_obj_set_y(ui_txtMosfetTmp, -89);
    lv_obj_set_align(ui_txtMosfetTmp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtMosfetTmp, "Mosfet TMP:");

    ui_lblMosfetTmp = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_lblMosfetTmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMosfetTmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMosfetTmp, -21);
    lv_obj_set_y(ui_lblMosfetTmp, -90);
    lv_obj_set_align(ui_lblMosfetTmp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMosfetTmp, "45°C");

    ui_txtERR = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_txtERR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtERR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtERR, -104);
    lv_obj_set_y(ui_txtERR, -39);
    lv_obj_set_align(ui_txtERR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtERR, "Err Code:");

    ui_lblERR = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_lblERR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblERR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblERR, -44);
    lv_obj_set_y(ui_lblERR, -39);
    lv_obj_set_align(ui_lblERR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblERR, "0 OK");

    ui_txtFW = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_txtFW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_txtFW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_txtFW, -121);
    lv_obj_set_y(ui_txtFW, 11);
    lv_obj_set_align(ui_txtFW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_txtFW, "FW:");

    ui_lblFW = lv_label_create(ui_scrSettings);
    lv_obj_set_width(ui_lblFW, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFW, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFW, -81);
    lv_obj_set_y(ui_lblFW, 11);
    lv_obj_set_align(ui_lblFW, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFW, " v1.6");

    ui_contGear = lv_obj_create(ui_scrSettings);
    lv_obj_remove_style_all(ui_contGear);
    lv_obj_set_width(ui_contGear, 69);
    lv_obj_set_height(ui_contGear, 66);
    lv_obj_set_x(ui_contGear, 106);
    lv_obj_set_y(ui_contGear, 124);
    lv_obj_set_align(ui_contGear, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contGear, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_contGear, &ui_img_1930944701, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_contGear, lv_color_hex(0xF1B63B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_contGear, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_scrSettings_screen_destroy(void)
{
    if(ui_scrSettings) lv_obj_del(ui_scrSettings);

    // NULL screen variables
    ui_scrSettings = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    ui_Panel3 = NULL;
    ui_Panel4 = NULL;
    ui_Panel5 = NULL;
    ui_Panel6 = NULL;
    ui_txtESCstatus = NULL;
    ui_lblESCstatus = NULL;
    ui_txtCPU = NULL;
    ui_lblCPU = NULL;
    ui_txtMosfetTmp = NULL;
    ui_lblMosfetTmp = NULL;
    ui_txtERR = NULL;
    ui_lblERR = NULL;
    ui_txtFW = NULL;
    ui_lblFW = NULL;
    ui_contGear = NULL;

}
